#!/usr/bin/env python3
"""Assemble the single-file index.html from src/ + FUNCTIONS.md.

    python3 build.py            rebuild index.html (and build/app.js for syntax checks)
    python3 build.py --check    rebuild in memory and fail if index.html is stale

The output is deterministic: same sources in, same bytes out. Nothing here may
embed a timestamp, a git SHA or a counter — --check and the CI job depend on it.

index.html carries NO company data, so it builds from the public sources alone.
If the two private files (src/company_data.json and src/workbook.xlsm) are also
present, this additionally packs them into build/Arctic Company File.arctic.
"""
import base64, json, os, re, html, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'index.html')
BUILD_DIR = os.path.join(ROOT, 'build')

BANNER = """<!-- ============================================================
     GENERATED FILE - DO NOT EDIT THIS FILE BY HAND.
     It is assembled from src/ by build.py. Anything typed in here is
     destroyed the next time anyone runs the build.
     To change the app:  edit src/parts/*.js  then run  python3 build.py
     ============================================================ -->
"""

def read(p): return open(os.path.join(SRC, p), encoding='utf-8').read()
def b64(path):
    with open(path, 'rb') as f:
        return base64.b64encode(f.read()).decode()

# ---- markdown-lite -> HTML for the in-app function map ----
def md_to_html(md):
    out, in_table, in_list, in_olist = [], False, False, False
    def inline(s):
        s = html.escape(s)
        s = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', s)
        s = re.sub(r'`([^`]+)`', r'<code>\1</code>', s)
        s = re.sub(r'\*(.+?)\*', r'<i>\1</i>', s)
        return s
    for line in md.splitlines():
        if line.startswith('|'):
            cells = [c.strip() for c in line.strip('|').split('|')]
            if re.match(r'^[\s\-|]+$', line):
                continue
            if not in_table:
                out.append('<div class="tablewrap"><table class="grid">')
                in_table = True
                out.append('<tr>' + ''.join(f'<th>{inline(c)}</th>' for c in cells) + '</tr>')
            else:
                out.append('<tr>' + ''.join(f'<td>{inline(c)}</td>' for c in cells) + '</tr>')
            continue
        if in_table:
            out.append('</table></div>')
            in_table = False
        if line.startswith('- '):
            if in_olist: out.append('</ol>'); in_olist = False
            if not in_list: out.append('<ul>'); in_list = True
            out.append(f'<li>{inline(line[2:])}</li>')
            continue
        ol = re.match(r'^(\d+)\. (.*)$', line)
        if ol:
            if in_list: out.append('</ul>'); in_list = False
            if not in_olist: out.append('<ol>'); in_olist = True
            out.append(f'<li>{inline(ol.group(2))}</li>')
            continue
        # an indented line right after a list item continues that item
        if (in_list or in_olist) and line.startswith('   ') and line.strip():
            out.append(f'<div class="licont">{inline(line.strip())}</div>')
            continue
        if in_list:
            out.append('</ul>'); in_list = False
        if in_olist:
            out.append('</ol>'); in_olist = False
        if line.startswith('###'): out.append(f'<h4>{inline(line[3:].strip())}</h4>')
        elif line.startswith('##'): out.append(f'<h3>{inline(line[2:].strip())}</h3>')
        elif line.startswith('#'): out.append(f'<h2 style="margin-top:0">{inline(line[1:].strip())}</h2>')
        elif line.strip(): out.append(f'<p>{inline(line)}</p>')
    if in_table: out.append('</table></div>')
    if in_list: out.append('</ul>')
    if in_olist: out.append('</ol>')
    return '\n'.join(out)

wordmark = b64(os.path.join(SRC, 'assets', 'wordmark.png'))
seal = b64(os.path.join(SRC, 'assets', 'seal.jpg'))
fnmap = md_to_html(open(os.path.join(ROOT, 'FUNCTIONS.md'), encoding='utf-8').read())
howto = md_to_html(open(os.path.join(ROOT, 'HOWTO.md'), encoding='utf-8').read())

# The rates and the workbook are deliberately NOT in this repository. They are
# only needed to pack the company file at the end of this script.
PRIVATE = {
    'rates': os.path.join(SRC, 'company_data.json'),
    'workbook': os.path.join(SRC, 'workbook.xlsm'),
}
missing_private = [p for p in PRIVATE.values() if not os.path.exists(p)]

def clean_lib(src):
    return re.sub(r"if \(typeof module[^\n]+\n", '', src)

def clean_part(src):
    return src.replace("'use strict';\n", '')

# The published page carries NO company data: no rates, no workbook. Those live in
# the company file (below), which Arctic keeps on its own network and each computer
# loads once. Only the logos and the function map are baked in.
data_js = (
    "let COMPANY = null;            // filled from the company file at startup\n"
    "let TEMPLATE_BYTES = null;     // the estimate workbook, from the same file\n"
    "const ASSETS = { wordmark: '" + wordmark + "', seal: '" + seal + "' };\n"
    "const FUNCTION_MAP_HTML = " + json.dumps(fnmap) + ";\n"
    "const HOWTO_HTML = " + json.dumps(howto) + ";\n"
)

js_parts = [
    'lib/pdf.js', 'lib/zip.js', 'lib/diff.js',           # infrastructure
    'parts/03_company.js', 'parts/06_fmt.js', 'parts/09_core.js', 'parts/04_model.js',
    'parts/05_engine.js', 'parts/05b_engine_recap.js', 'parts/05c_engine_indirects.js', 'parts/05d_engine_booking.js',
    'parts/07a_ui_helpers.js', 'parts/07b_ui_recap.js', 'parts/07c_ui_takeoff.js', 'parts/07d_ui_crew.js',
    'parts/07e_ui_smimport.js', 'parts/07f_ui_indirects.js', 'parts/07g_ui_outputs.js', 'parts/07h_ui_settings.js',
    'parts/07i_ui_keynav.js', 'parts/07j_ui_howto.js',
    'parts/08_io.js', 'parts/11_pdf_pages.js', 'parts/12_xlsm.js', 'parts/10_home.js',
]

js = "'use strict';\n" + data_js
for p in js_parts:
    src = read(p)
    src = clean_lib(src) if p.startswith('lib/') else src
    js += '\n// ===== ' + p + ' =====\n' + clean_part(src)

body = read('parts/02_body.html')
assert '</body>' in body
body = body.replace('</body>', '<script>\n' + js + '\n</script>\n</body>')

html_out = read('parts/01_head.html') + body + '\n</html>\n'
# banner goes AFTER the doctype (a comment before it triggers quirks mode)
html_out = html_out.replace('<!DOCTYPE html>\n', '<!DOCTYPE html>\n' + BANNER, 1)

if '--check' in sys.argv:
    current = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else None
    if current == html_out:
        print('index.html is up to date with src/')
        sys.exit(0)
    print('STALE: index.html does not match a fresh build of src/.', file=sys.stderr)
    print('Run:  python3 build.py    and commit index.html', file=sys.stderr)
    sys.exit(1)

with open(OUT, 'w', encoding='utf-8') as f:
    f.write(html_out)
# the concatenated app JS on its own, so `node --check build/app.js` can parse it
os.makedirs(BUILD_DIR, exist_ok=True)
with open(os.path.join(BUILD_DIR, 'app.js'), 'w', encoding='utf-8') as f:
    f.write(js)
print(f'wrote {OUT}: {os.path.getsize(OUT)//1024}KB   (+ build/app.js for syntax checks)')

# ---- the company file: everything the published page deliberately does not carry ----
if missing_private:
    print('\nSkipped the company file — these are not in this checkout:')
    for p in missing_private:
        print('   ' + os.path.relpath(p, ROOT))
    print('That is normal and correct: they are kept off the public repository.')
    print('index.html above is complete and does not need them. To pack a company')
    print('file, copy those two out of the Arctic company file into src/ first.')
    print('See DEVELOPING.md, "The two files that are not in this repository".')
    sys.exit(0)

import zipfile
COMPANY_FILE = os.path.join(BUILD_DIR, 'Arctic Company File.arctic')
with zipfile.ZipFile(COMPANY_FILE, 'w', zipfile.ZIP_DEFLATED) as z:
    z.write(PRIVATE['rates'], 'company_data.json')
    z.write(PRIVATE['workbook'], 'workbook.xlsm')
    z.writestr('README.txt',
               'Arctic Bid Tool - company file\n\n'
               'Holds the rate tables and the estimate workbook. Keep it on the Arctic\n'
               'network, NOT in the public repository and NOT on the website.\n\n'
               'Each computer loads it once: open the bid tool and drop this file on the\n'
               'setup screen. To roll out new rates, replace this file and load it again\n'
               'from Company Settings.\n')
print(f'wrote {COMPANY_FILE}: {os.path.getsize(COMPANY_FILE)//1024}KB  (keep this OFF the public site)')
